-- MySQL Script generated by MySQL Workbench
-- Wed Jun 27 16:54:46 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema clubpp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema clubpp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clubpp` DEFAULT CHARACTER SET utf8 ;
USE `clubpp` ;

-- -----------------------------------------------------
-- Table `clubpp`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clubpp`.`user` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `day_of_birth` DATE NULL DEFAULT NULL,
  `password` VARCHAR(100) NULL DEFAULT NULL,
  `gender` TINYINT(1) NULL DEFAULT NULL,
  `academy` VARCHAR(45) NULL DEFAULT NULL,
  `major` VARCHAR(45) NULL DEFAULT NULL,
  `bio` VARCHAR(45) NULL DEFAULT NULL,
  `avatar_path` VARCHAR(100) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `is_admin` TINYINT(1) NULL,
  `year_of_enrollment` INT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `clubpp`.`club`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clubpp`.`club` (
  `club_id` INT(11) NOT NULL AUTO_INCREMENT,
  `club_name` VARCHAR(45) NULL DEFAULT NULL,
  `created_date` DATE NULL DEFAULT NULL,
  `menber_number` INT(11) NULL DEFAULT NULL,
  `club_bio` VARCHAR(45) NULL DEFAULT NULL,
  `tags` VARCHAR(45) NULL DEFAULT NULL,
  `addresses` VARCHAR(255) NULL DEFAULT NULL,
  `master_id` INT(11) NOT NULL,
  `is_passed` TINYINT(1) NULL,
  PRIMARY KEY (`club_id`),
  INDEX `fk_club_user_idx` (`master_id` ASC),
  CONSTRAINT `fk_club_user`
    FOREIGN KEY (`master_id`)
    REFERENCES `clubpp`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `clubpp`.`request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clubpp`.`request` (
  `user_id` INT(11) NOT NULL,
  `club_id` INT(11) NOT NULL,
  `request_id` VARCHAR(45) NOT NULL,
  `time` TIMESTAMP NULL DEFAULT C0RRENT_TIMESTAMP,
  `extra` VARCHAR(100) NULL,
  `is_read` TINYINT(1) NULL,
  INDEX `fk_user_has_club_club1_idx` (`club_id` ASC),
  INDEX `fk_user_has_club_user1_idx` (`user_id` ASC),
  PRIMARY KEY (`request_id`),
  CONSTRAINT `fk_user_has_club_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `clubpp`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_club_club1`
    FOREIGN KEY (`club_id`)
    REFERENCES `clubpp`.`club` (`club_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `clubpp`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clubpp`.`image` (
  `club_id` INT(11) NOT NULL,
  `image_path` VARCHAR(255) NULL,
  `image_id` INT NULL AUTO_INCREMENT,
  INDEX `fk_table1_club1_idx` (`club_id` ASC),
  CONSTRAINT `fk_table1_club1`
    FOREIGN KEY (`club_id`)
    REFERENCES `clubpp`.`club` (`club_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
